name: Generate Pages and Synchronize to Mirror Repository

on:
  push:
    branches:
    - master

env:
  LANG: "zh_CN.UTF-8"

jobs:
  build-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Locale
      run: |
        sudo locale-gen zh_CN.UTF-8
        sudo update-locale LANG=zh_CN.UTF-8

    - name: Install system packages
      run: |
        sudo apt-get install fonts-droid-fallback ttf-dejavu ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-ukai fonts-arphic-uming
        sudo apt-get install wget xfonts-base xfonts-75dpi
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
        sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
        wget http://security.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb
        sudo dpkg -i libpng12-0_1.2.54-1ubuntu1.1_amd64.deb
        wget https://launchpad.net/~ubuntu-security/+archive/ubuntu/ppa/+build/15108504/+files/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb
        sudo dpkg -i libpng12-0_1.2.54-1ubuntu1.1_amd64.deb
        wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.5-1.xenial_amd64.deb
        sudo apt-get install xvfb
        sudo apt-get install firefox

    - name: Setup wkhtmltopdf tool
      run: |
        sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin/wkhtmltopdf_bin
        echo -e '#!/bin/bash\nxvfb-run -a --server-args="-screen 0, 1024x768x24" /usr/bin/wkhtmltopdf_bin -q $*' | sudo tee /usr/bin/wkhtmltopdf
        sudo chmod a+x /usr/bin/wkhtmltopdf

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generate HTML pages and other files
      run: |
        python run.py --to all --server
        cd output
        if [ -f cn/print.html ]; then rm cn/print.html ; fi
        if [ -f en/print.html ]; then rm en/print.html ; fi
        cd ../

    - name: Deploy github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true

